### ISSUE TITLE
Latest tested version is inconsistent with requirements

### ISSUE THREAD

**Issue by ScallyGames** [Unity-Technologies/ECS-Network-Racing-Sample#6]
According to https://github.com/Unity-Technologies/ECS-Network-Racing-Sample/blob/master/README.md#8 the current tested version is 2022.2.9f1. This is inconsistent with the requirement of Unity 2022.3.0f1 or later described above.

Is this a typo and should it be 2022.3.9f1 or have there been changes on the requirement and the latest tested version was not updated?

**Comment by nick-morhun** [comment]
ProjectVersion.txt says 2022.3.6f1 on master branch.

**Comment by ScallyGames** [comment]
Good spot. The link for the current version points to 2022.3.0. There just seem to be some inconsistencies in the README.md, probably just an oversight after updating.

**Comment by julianunity** [comment]
Thanks for the feedback, I have updated to Unity 6 and also the readme file. 

Please try the updated version on Unity 6, which includes improvements and script updates in the latest commit.
Be sure to clone the project rather than downloading it directly.
I look forward to your feedback and will be available for any questions.
